/*
 * Produto
 * Serviço de Produto do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.produto.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.erpx.fnd.produto.pojos.E012fam;
import br.com.senior.erpx.fnd.produto.pojos.E084mas;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * E012fxm
 */

public class E012fxm {
  @SerializedName("usualt")
  private String usualt = null;

  @SerializedName("seqMpr")
  private Integer seqMpr = null;

  @SerializedName("e084mas")
  private E084mas e084mas = null;

  @SerializedName("dthger")
  private OffsetDateTime dthger = null;

  @SerializedName("dthalt")
  private OffsetDateTime dthalt = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("e012fam")
  private E012fam e012fam = null;

  @SerializedName("usuger")
  private String usuger = null;

  public E012fxm usualt(String usualt) {
    this.usualt = usualt;
    return this;
  }

   /**
   * 
   * @return usualt
  **/
  @ApiModelProperty(value = "")
  public String getUsualt() {
    return usualt;
  }

  public void setUsualt(String usualt) {
    this.usualt = usualt;
  }

  public E012fxm seqMpr(Integer seqMpr) {
    this.seqMpr = seqMpr;
    return this;
  }

   /**
   * Ordem da máscara na família
   * @return seqMpr
  **/
  @ApiModelProperty(required = true, value = "Ordem da máscara na família")
  public Integer getSeqMpr() {
    return seqMpr;
  }

  public void setSeqMpr(Integer seqMpr) {
    this.seqMpr = seqMpr;
  }

  public E012fxm e084mas(E084mas e084mas) {
    this.e084mas = e084mas;
    return this;
  }

   /**
   * Get e084mas
   * @return e084mas
  **/
  @ApiModelProperty(required = true, value = "")
  public E084mas getE084mas() {
    return e084mas;
  }

  public void setE084mas(E084mas e084mas) {
    this.e084mas = e084mas;
  }

  public E012fxm dthger(OffsetDateTime dthger) {
    this.dthger = dthger;
    return this;
  }

   /**
   * 
   * @return dthger
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthger() {
    return dthger;
  }

  public void setDthger(OffsetDateTime dthger) {
    this.dthger = dthger;
  }

  public E012fxm dthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
    return this;
  }

   /**
   * 
   * @return dthalt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthalt() {
    return dthalt;
  }

  public void setDthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
  }

  public E012fxm id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public E012fxm e012fam(E012fam e012fam) {
    this.e012fam = e012fam;
    return this;
  }

   /**
   * Get e012fam
   * @return e012fam
  **/
  @ApiModelProperty(value = "")
  public E012fam getE012fam() {
    return e012fam;
  }

  public void setE012fam(E012fam e012fam) {
    this.e012fam = e012fam;
  }

  public E012fxm usuger(String usuger) {
    this.usuger = usuger;
    return this;
  }

   /**
   * 
   * @return usuger
  **/
  @ApiModelProperty(value = "")
  public String getUsuger() {
    return usuger;
  }

  public void setUsuger(String usuger) {
    this.usuger = usuger;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    E012fxm e012fxm = (E012fxm) o;
    return Objects.equals(this.usualt, e012fxm.usualt) &&
        Objects.equals(this.seqMpr, e012fxm.seqMpr) &&
        Objects.equals(this.e084mas, e012fxm.e084mas) &&
        Objects.equals(this.dthger, e012fxm.dthger) &&
        Objects.equals(this.dthalt, e012fxm.dthalt) &&
        Objects.equals(this.id, e012fxm.id) &&
        Objects.equals(this.e012fam, e012fxm.e012fam) &&
        Objects.equals(this.usuger, e012fxm.usuger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usualt, seqMpr, e084mas, dthger, dthalt, id, e012fam, usuger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class E012fxm {\n");
    
    sb.append("    usualt: ").append(toIndentedString(usualt)).append("\n");
    sb.append("    seqMpr: ").append(toIndentedString(seqMpr)).append("\n");
    sb.append("    e084mas: ").append(toIndentedString(e084mas)).append("\n");
    sb.append("    dthger: ").append(toIndentedString(dthger)).append("\n");
    sb.append("    dthalt: ").append(toIndentedString(dthalt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    e012fam: ").append(toIndentedString(e012fam)).append("\n");
    sb.append("    usuger: ").append(toIndentedString(usuger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

