/*
 * Produto
 * Serviço de Produto do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.produto.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.erpx.fnd.produto.pojos.E012fxm;
import br.com.senior.erpx.fnd.produto.pojos.E047ntg;
import br.com.senior.erpx.fnd.produto.pojos.E070emp;
import br.com.senior.erpx.fnd.produto.pojos.E076mar;
import br.com.senior.erpx.fnd.produto.pojos.E083ori;
import br.com.senior.erpx.fnd.produto.pojos.EnumExiMon;
import br.com.senior.erpx.fnd.produto.pojos.EnumSitReg;
import br.com.senior.erpx.fnd.produto.pojos.EnumTipPro;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * E012fam
 */

public class E012fam {
  @SerializedName("codFam")
  private String codFam = null;

  @SerializedName("usualt")
  private String usualt = null;

  @SerializedName("excluido")
  private Boolean excluido = null;

  @SerializedName("dthger")
  private OffsetDateTime dthger = null;

  @SerializedName("e047ntg")
  private E047ntg e047ntg = null;

  @SerializedName("proMon")
  private EnumExiMon proMon = null;

  @SerializedName("e012fxm")
  private List<E012fxm> e012fxm = null;

  @SerializedName("desFam")
  private String desFam = null;

  @SerializedName("posPro")
  private Integer posPro = null;

  @SerializedName("dthalt")
  private OffsetDateTime dthalt = null;

  @SerializedName("e076mar")
  private E076mar e076mar = null;

  @SerializedName("e083ori")
  private E083ori e083ori = null;

  @SerializedName("sitFam")
  private EnumSitReg sitFam = null;

  @SerializedName("usuger")
  private String usuger = null;

  @SerializedName("e070emp")
  private E070emp e070emp = null;

  @SerializedName("numOri")
  private Integer numOri = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("indKit")
  private Boolean indKit = null;

  @SerializedName("tipPro")
  private EnumTipPro tipPro = null;

  public E012fam codFam(String codFam) {
    this.codFam = codFam;
    return this;
  }

   /**
   * Código
   * @return codFam
  **/
  @ApiModelProperty(required = true, value = "Código")
  public String getCodFam() {
    return codFam;
  }

  public void setCodFam(String codFam) {
    this.codFam = codFam;
  }

  public E012fam usualt(String usualt) {
    this.usualt = usualt;
    return this;
  }

   /**
   * 
   * @return usualt
  **/
  @ApiModelProperty(value = "")
  public String getUsualt() {
    return usualt;
  }

  public void setUsualt(String usualt) {
    this.usualt = usualt;
  }

  public E012fam excluido(Boolean excluido) {
    this.excluido = excluido;
    return this;
  }

   /**
   * Indica se o registro foi excluído
   * @return excluido
  **/
  @ApiModelProperty(value = "Indica se o registro foi excluído")
  public Boolean isExcluido() {
    return excluido;
  }

  public void setExcluido(Boolean excluido) {
    this.excluido = excluido;
  }

  public E012fam dthger(OffsetDateTime dthger) {
    this.dthger = dthger;
    return this;
  }

   /**
   * 
   * @return dthger
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthger() {
    return dthger;
  }

  public void setDthger(OffsetDateTime dthger) {
    this.dthger = dthger;
  }

  public E012fam e047ntg(E047ntg e047ntg) {
    this.e047ntg = e047ntg;
    return this;
  }

   /**
   * Get e047ntg
   * @return e047ntg
  **/
  @ApiModelProperty(value = "")
  public E047ntg getE047ntg() {
    return e047ntg;
  }

  public void setE047ntg(E047ntg e047ntg) {
    this.e047ntg = e047ntg;
  }

  public E012fam proMon(EnumExiMon proMon) {
    this.proMon = proMon;
    return this;
  }

   /**
   * Get proMon
   * @return proMon
  **/
  @ApiModelProperty(value = "")
  public EnumExiMon getProMon() {
    return proMon;
  }

  public void setProMon(EnumExiMon proMon) {
    this.proMon = proMon;
  }

  public E012fam e012fxm(List<E012fxm> e012fxm) {
    this.e012fxm = e012fxm;
    return this;
  }

  public E012fam addE012fxmItem(E012fxm e012fxmItem) {
    if (this.e012fxm == null) {
      this.e012fxm = new ArrayList<E012fxm>();
    }
    this.e012fxm.add(e012fxmItem);
    return this;
  }

   /**
   * Ligacação família - máscara
   * @return e012fxm
  **/
  @ApiModelProperty(value = "Ligacação família - máscara")
  public List<E012fxm> getE012fxm() {
    return e012fxm;
  }

  public void setE012fxm(List<E012fxm> e012fxm) {
    this.e012fxm = e012fxm;
  }

  public E012fam desFam(String desFam) {
    this.desFam = desFam;
    return this;
  }

   /**
   * Descrição
   * @return desFam
  **/
  @ApiModelProperty(required = true, value = "Descrição")
  public String getDesFam() {
    return desFam;
  }

  public void setDesFam(String desFam) {
    this.desFam = desFam;
  }

  public E012fam posPro(Integer posPro) {
    this.posPro = posPro;
    return this;
  }

   /**
   * Quantidade de posições para o código de produto
   * @return posPro
  **/
  @ApiModelProperty(required = true, value = "Quantidade de posições para o código de produto")
  public Integer getPosPro() {
    return posPro;
  }

  public void setPosPro(Integer posPro) {
    this.posPro = posPro;
  }

  public E012fam dthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
    return this;
  }

   /**
   * 
   * @return dthalt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthalt() {
    return dthalt;
  }

  public void setDthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
  }

  public E012fam e076mar(E076mar e076mar) {
    this.e076mar = e076mar;
    return this;
  }

   /**
   * Get e076mar
   * @return e076mar
  **/
  @ApiModelProperty(value = "")
  public E076mar getE076mar() {
    return e076mar;
  }

  public void setE076mar(E076mar e076mar) {
    this.e076mar = e076mar;
  }

  public E012fam e083ori(E083ori e083ori) {
    this.e083ori = e083ori;
    return this;
  }

   /**
   * Get e083ori
   * @return e083ori
  **/
  @ApiModelProperty(required = true, value = "")
  public E083ori getE083ori() {
    return e083ori;
  }

  public void setE083ori(E083ori e083ori) {
    this.e083ori = e083ori;
  }

  public E012fam sitFam(EnumSitReg sitFam) {
    this.sitFam = sitFam;
    return this;
  }

   /**
   * Get sitFam
   * @return sitFam
  **/
  @ApiModelProperty(value = "")
  public EnumSitReg getSitFam() {
    return sitFam;
  }

  public void setSitFam(EnumSitReg sitFam) {
    this.sitFam = sitFam;
  }

  public E012fam usuger(String usuger) {
    this.usuger = usuger;
    return this;
  }

   /**
   * 
   * @return usuger
  **/
  @ApiModelProperty(value = "")
  public String getUsuger() {
    return usuger;
  }

  public void setUsuger(String usuger) {
    this.usuger = usuger;
  }

  public E012fam e070emp(E070emp e070emp) {
    this.e070emp = e070emp;
    return this;
  }

   /**
   * Get e070emp
   * @return e070emp
  **/
  @ApiModelProperty(required = true, value = "")
  public E070emp getE070emp() {
    return e070emp;
  }

  public void setE070emp(E070emp e070emp) {
    this.e070emp = e070emp;
  }

  public E012fam numOri(Integer numOri) {
    this.numOri = numOri;
    return this;
  }

   /**
   * Número do nível da origem do produto
   * @return numOri
  **/
  @ApiModelProperty(value = "Número do nível da origem do produto")
  public Integer getNumOri() {
    return numOri;
  }

  public void setNumOri(Integer numOri) {
    this.numOri = numOri;
  }

  public E012fam id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public E012fam indKit(Boolean indKit) {
    this.indKit = indKit;
    return this;
  }

   /**
   * Indicativo que os produtos produzidos desta família são &amp;#39;kit&amp;#39; c/ vários produtos agregados p/ venda (não gera op)
   * @return indKit
  **/
  @ApiModelProperty(required = true, value = "Indicativo que os produtos produzidos desta família são &#39;kit&#39; c/ vários produtos agregados p/ venda (não gera op)")
  public Boolean isIndKit() {
    return indKit;
  }

  public void setIndKit(Boolean indKit) {
    this.indKit = indKit;
  }

  public E012fam tipPro(EnumTipPro tipPro) {
    this.tipPro = tipPro;
    return this;
  }

   /**
   * Get tipPro
   * @return tipPro
  **/
  @ApiModelProperty(value = "")
  public EnumTipPro getTipPro() {
    return tipPro;
  }

  public void setTipPro(EnumTipPro tipPro) {
    this.tipPro = tipPro;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    E012fam e012fam = (E012fam) o;
    return Objects.equals(this.codFam, e012fam.codFam) &&
        Objects.equals(this.usualt, e012fam.usualt) &&
        Objects.equals(this.excluido, e012fam.excluido) &&
        Objects.equals(this.dthger, e012fam.dthger) &&
        Objects.equals(this.e047ntg, e012fam.e047ntg) &&
        Objects.equals(this.proMon, e012fam.proMon) &&
        Objects.equals(this.e012fxm, e012fam.e012fxm) &&
        Objects.equals(this.desFam, e012fam.desFam) &&
        Objects.equals(this.posPro, e012fam.posPro) &&
        Objects.equals(this.dthalt, e012fam.dthalt) &&
        Objects.equals(this.e076mar, e012fam.e076mar) &&
        Objects.equals(this.e083ori, e012fam.e083ori) &&
        Objects.equals(this.sitFam, e012fam.sitFam) &&
        Objects.equals(this.usuger, e012fam.usuger) &&
        Objects.equals(this.e070emp, e012fam.e070emp) &&
        Objects.equals(this.numOri, e012fam.numOri) &&
        Objects.equals(this.id, e012fam.id) &&
        Objects.equals(this.indKit, e012fam.indKit) &&
        Objects.equals(this.tipPro, e012fam.tipPro);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codFam, usualt, excluido, dthger, e047ntg, proMon, e012fxm, desFam, posPro, dthalt, e076mar, e083ori, sitFam, usuger, e070emp, numOri, id, indKit, tipPro);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class E012fam {\n");
    
    sb.append("    codFam: ").append(toIndentedString(codFam)).append("\n");
    sb.append("    usualt: ").append(toIndentedString(usualt)).append("\n");
    sb.append("    excluido: ").append(toIndentedString(excluido)).append("\n");
    sb.append("    dthger: ").append(toIndentedString(dthger)).append("\n");
    sb.append("    e047ntg: ").append(toIndentedString(e047ntg)).append("\n");
    sb.append("    proMon: ").append(toIndentedString(proMon)).append("\n");
    sb.append("    e012fxm: ").append(toIndentedString(e012fxm)).append("\n");
    sb.append("    desFam: ").append(toIndentedString(desFam)).append("\n");
    sb.append("    posPro: ").append(toIndentedString(posPro)).append("\n");
    sb.append("    dthalt: ").append(toIndentedString(dthalt)).append("\n");
    sb.append("    e076mar: ").append(toIndentedString(e076mar)).append("\n");
    sb.append("    e083ori: ").append(toIndentedString(e083ori)).append("\n");
    sb.append("    sitFam: ").append(toIndentedString(sitFam)).append("\n");
    sb.append("    usuger: ").append(toIndentedString(usuger)).append("\n");
    sb.append("    e070emp: ").append(toIndentedString(e070emp)).append("\n");
    sb.append("    numOri: ").append(toIndentedString(numOri)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    indKit: ").append(toIndentedString(indKit)).append("\n");
    sb.append("    tipPro: ").append(toIndentedString(tipPro)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

