/*
 * Produto
 * Serviço de Produto do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.produto.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.erpx.fnd.produto.pojos.E070emp;
import br.com.senior.erpx.fnd.produto.pojos.EnumTipNtg;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * E047ntg
 */

public class E047ntg {
  @SerializedName("usualt")
  private String usualt = null;

  @SerializedName("excluido")
  private Boolean excluido = null;

  @SerializedName("codNtg")
  private Integer codNtg = null;

  @SerializedName("dthger")
  private OffsetDateTime dthger = null;

  @SerializedName("desNtg")
  private String desNtg = null;

  @SerializedName("e070emp")
  private E070emp e070emp = null;

  @SerializedName("dthalt")
  private OffsetDateTime dthalt = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("tipNtg")
  private EnumTipNtg tipNtg = null;

  @SerializedName("usuger")
  private String usuger = null;

  public E047ntg usualt(String usualt) {
    this.usualt = usualt;
    return this;
  }

   /**
   * 
   * @return usualt
  **/
  @ApiModelProperty(value = "")
  public String getUsualt() {
    return usualt;
  }

  public void setUsualt(String usualt) {
    this.usualt = usualt;
  }

  public E047ntg excluido(Boolean excluido) {
    this.excluido = excluido;
    return this;
  }

   /**
   * Indica se o registro foi excluído
   * @return excluido
  **/
  @ApiModelProperty(value = "Indica se o registro foi excluído")
  public Boolean isExcluido() {
    return excluido;
  }

  public void setExcluido(Boolean excluido) {
    this.excluido = excluido;
  }

  public E047ntg codNtg(Integer codNtg) {
    this.codNtg = codNtg;
    return this;
  }

   /**
   * Natureza de Gasto
   * @return codNtg
  **/
  @ApiModelProperty(required = true, value = "Natureza de Gasto")
  public Integer getCodNtg() {
    return codNtg;
  }

  public void setCodNtg(Integer codNtg) {
    this.codNtg = codNtg;
  }

  public E047ntg dthger(OffsetDateTime dthger) {
    this.dthger = dthger;
    return this;
  }

   /**
   * 
   * @return dthger
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthger() {
    return dthger;
  }

  public void setDthger(OffsetDateTime dthger) {
    this.dthger = dthger;
  }

  public E047ntg desNtg(String desNtg) {
    this.desNtg = desNtg;
    return this;
  }

   /**
   * Descrição
   * @return desNtg
  **/
  @ApiModelProperty(required = true, value = "Descrição")
  public String getDesNtg() {
    return desNtg;
  }

  public void setDesNtg(String desNtg) {
    this.desNtg = desNtg;
  }

  public E047ntg e070emp(E070emp e070emp) {
    this.e070emp = e070emp;
    return this;
  }

   /**
   * Get e070emp
   * @return e070emp
  **/
  @ApiModelProperty(required = true, value = "")
  public E070emp getE070emp() {
    return e070emp;
  }

  public void setE070emp(E070emp e070emp) {
    this.e070emp = e070emp;
  }

  public E047ntg dthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
    return this;
  }

   /**
   * 
   * @return dthalt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthalt() {
    return dthalt;
  }

  public void setDthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
  }

  public E047ntg id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public E047ntg tipNtg(EnumTipNtg tipNtg) {
    this.tipNtg = tipNtg;
    return this;
  }

   /**
   * Get tipNtg
   * @return tipNtg
  **/
  @ApiModelProperty(required = true, value = "")
  public EnumTipNtg getTipNtg() {
    return tipNtg;
  }

  public void setTipNtg(EnumTipNtg tipNtg) {
    this.tipNtg = tipNtg;
  }

  public E047ntg usuger(String usuger) {
    this.usuger = usuger;
    return this;
  }

   /**
   * 
   * @return usuger
  **/
  @ApiModelProperty(value = "")
  public String getUsuger() {
    return usuger;
  }

  public void setUsuger(String usuger) {
    this.usuger = usuger;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    E047ntg e047ntg = (E047ntg) o;
    return Objects.equals(this.usualt, e047ntg.usualt) &&
        Objects.equals(this.excluido, e047ntg.excluido) &&
        Objects.equals(this.codNtg, e047ntg.codNtg) &&
        Objects.equals(this.dthger, e047ntg.dthger) &&
        Objects.equals(this.desNtg, e047ntg.desNtg) &&
        Objects.equals(this.e070emp, e047ntg.e070emp) &&
        Objects.equals(this.dthalt, e047ntg.dthalt) &&
        Objects.equals(this.id, e047ntg.id) &&
        Objects.equals(this.tipNtg, e047ntg.tipNtg) &&
        Objects.equals(this.usuger, e047ntg.usuger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usualt, excluido, codNtg, dthger, desNtg, e070emp, dthalt, id, tipNtg, usuger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class E047ntg {\n");
    
    sb.append("    usualt: ").append(toIndentedString(usualt)).append("\n");
    sb.append("    excluido: ").append(toIndentedString(excluido)).append("\n");
    sb.append("    codNtg: ").append(toIndentedString(codNtg)).append("\n");
    sb.append("    dthger: ").append(toIndentedString(dthger)).append("\n");
    sb.append("    desNtg: ").append(toIndentedString(desNtg)).append("\n");
    sb.append("    e070emp: ").append(toIndentedString(e070emp)).append("\n");
    sb.append("    dthalt: ").append(toIndentedString(dthalt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tipNtg: ").append(toIndentedString(tipNtg)).append("\n");
    sb.append("    usuger: ").append(toIndentedString(usuger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

