/*
 * Produto
 * Serviço de Produto do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.produto.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * E070emp
 */

public class E070emp {
  @SerializedName("usualt")
  private String usualt = null;

  @SerializedName("sigEmp")
  private String sigEmp = null;

  @SerializedName("dthger")
  private OffsetDateTime dthger = null;

  @SerializedName("dthalt")
  private OffsetDateTime dthalt = null;

  @SerializedName("codEmp")
  private Integer codEmp = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("nomEmp")
  private String nomEmp = null;

  @SerializedName("usuger")
  private String usuger = null;

  public E070emp usualt(String usualt) {
    this.usualt = usualt;
    return this;
  }

   /**
   * 
   * @return usualt
  **/
  @ApiModelProperty(value = "")
  public String getUsualt() {
    return usualt;
  }

  public void setUsualt(String usualt) {
    this.usualt = usualt;
  }

  public E070emp sigEmp(String sigEmp) {
    this.sigEmp = sigEmp;
    return this;
  }

   /**
   * Nome fantasia da empresa
   * @return sigEmp
  **/
  @ApiModelProperty(required = true, value = "Nome fantasia da empresa")
  public String getSigEmp() {
    return sigEmp;
  }

  public void setSigEmp(String sigEmp) {
    this.sigEmp = sigEmp;
  }

  public E070emp dthger(OffsetDateTime dthger) {
    this.dthger = dthger;
    return this;
  }

   /**
   * 
   * @return dthger
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthger() {
    return dthger;
  }

  public void setDthger(OffsetDateTime dthger) {
    this.dthger = dthger;
  }

  public E070emp dthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
    return this;
  }

   /**
   * 
   * @return dthalt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthalt() {
    return dthalt;
  }

  public void setDthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
  }

  public E070emp codEmp(Integer codEmp) {
    this.codEmp = codEmp;
    return this;
  }

   /**
   * Código da empresa
   * @return codEmp
  **/
  @ApiModelProperty(required = true, value = "Código da empresa")
  public Integer getCodEmp() {
    return codEmp;
  }

  public void setCodEmp(Integer codEmp) {
    this.codEmp = codEmp;
  }

  public E070emp id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public E070emp nomEmp(String nomEmp) {
    this.nomEmp = nomEmp;
    return this;
  }

   /**
   * Nome da empresa
   * @return nomEmp
  **/
  @ApiModelProperty(required = true, value = "Nome da empresa")
  public String getNomEmp() {
    return nomEmp;
  }

  public void setNomEmp(String nomEmp) {
    this.nomEmp = nomEmp;
  }

  public E070emp usuger(String usuger) {
    this.usuger = usuger;
    return this;
  }

   /**
   * 
   * @return usuger
  **/
  @ApiModelProperty(value = "")
  public String getUsuger() {
    return usuger;
  }

  public void setUsuger(String usuger) {
    this.usuger = usuger;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    E070emp e070emp = (E070emp) o;
    return Objects.equals(this.usualt, e070emp.usualt) &&
        Objects.equals(this.sigEmp, e070emp.sigEmp) &&
        Objects.equals(this.dthger, e070emp.dthger) &&
        Objects.equals(this.dthalt, e070emp.dthalt) &&
        Objects.equals(this.codEmp, e070emp.codEmp) &&
        Objects.equals(this.id, e070emp.id) &&
        Objects.equals(this.nomEmp, e070emp.nomEmp) &&
        Objects.equals(this.usuger, e070emp.usuger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usualt, sigEmp, dthger, dthalt, codEmp, id, nomEmp, usuger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class E070emp {\n");
    
    sb.append("    usualt: ").append(toIndentedString(usualt)).append("\n");
    sb.append("    sigEmp: ").append(toIndentedString(sigEmp)).append("\n");
    sb.append("    dthger: ").append(toIndentedString(dthger)).append("\n");
    sb.append("    dthalt: ").append(toIndentedString(dthalt)).append("\n");
    sb.append("    codEmp: ").append(toIndentedString(codEmp)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nomEmp: ").append(toIndentedString(nomEmp)).append("\n");
    sb.append("    usuger: ").append(toIndentedString(usuger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

