/*
 * Produto
 * Serviço de Produto do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.produto.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.erpx.fnd.produto.pojos.E012fam;
import br.com.senior.erpx.fnd.produto.pojos.E021mot;
import br.com.senior.erpx.fnd.produto.pojos.E047ntg;
import br.com.senior.erpx.fnd.produto.pojos.E070emp;
import br.com.senior.erpx.fnd.produto.pojos.EnumProEpe;
import br.com.senior.erpx.fnd.produto.pojos.EnumSitReg;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * E075der
 */

public class E075der {
  @SerializedName("usualt")
  private String usualt = null;

  @SerializedName("codBar")
  private String codBar = null;

  @SerializedName("codBa2")
  private String codBa2 = null;

  @SerializedName("codRef")
  private String codRef = null;

  @SerializedName("excluido")
  private Boolean excluido = null;

  @SerializedName("codDer")
  private String codDer = null;

  @SerializedName("desCpl")
  private String desCpl = null;

  @SerializedName("pesBru")
  private Double pesBru = null;

  @SerializedName("dthger")
  private OffsetDateTime dthger = null;

  @SerializedName("e047ntg")
  private E047ntg e047ntg = null;

  @SerializedName("sitDer")
  private EnumSitReg sitDer = null;

  @SerializedName("dthalt")
  private OffsetDateTime dthalt = null;

  @SerializedName("e012fam")
  private E012fam e012fam = null;

  @SerializedName("usuger")
  private String usuger = null;

  @SerializedName("codGtn")
  private String codGtn = null;

  @SerializedName("pesLiq")
  private Double pesLiq = null;

  @SerializedName("proEpe")
  private EnumProEpe proEpe = null;

  @SerializedName("desDer")
  private String desDer = null;

  @SerializedName("e070emp")
  private E070emp e070emp = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("idePro")
  private String idePro = null;

  @SerializedName("e021mot")
  private E021mot e021mot = null;

  public E075der usualt(String usualt) {
    this.usualt = usualt;
    return this;
  }

   /**
   * 
   * @return usualt
  **/
  @ApiModelProperty(value = "")
  public String getUsualt() {
    return usualt;
  }

  public void setUsualt(String usualt) {
    this.usualt = usualt;
  }

  public E075der codBar(String codBar) {
    this.codBar = codBar;
    return this;
  }

   /**
   * Código de barras
   * @return codBar
  **/
  @ApiModelProperty(value = "Código de barras")
  public String getCodBar() {
    return codBar;
  }

  public void setCodBar(String codBar) {
    this.codBar = codBar;
  }

  public E075der codBa2(String codBa2) {
    this.codBa2 = codBa2;
    return this;
  }

   /**
   * Código barras livre
   * @return codBa2
  **/
  @ApiModelProperty(value = "Código barras livre")
  public String getCodBa2() {
    return codBa2;
  }

  public void setCodBa2(String codBa2) {
    this.codBa2 = codBa2;
  }

  public E075der codRef(String codRef) {
    this.codRef = codRef;
    return this;
  }

   /**
   * Código da Referência
   * @return codRef
  **/
  @ApiModelProperty(value = "Código da Referência")
  public String getCodRef() {
    return codRef;
  }

  public void setCodRef(String codRef) {
    this.codRef = codRef;
  }

  public E075der excluido(Boolean excluido) {
    this.excluido = excluido;
    return this;
  }

   /**
   * Indica se o registro foi excluído
   * @return excluido
  **/
  @ApiModelProperty(value = "Indica se o registro foi excluído")
  public Boolean isExcluido() {
    return excluido;
  }

  public void setExcluido(Boolean excluido) {
    this.excluido = excluido;
  }

  public E075der codDer(String codDer) {
    this.codDer = codDer;
    return this;
  }

   /**
   * Derivação
   * @return codDer
  **/
  @ApiModelProperty(required = true, value = "Derivação")
  public String getCodDer() {
    return codDer;
  }

  public void setCodDer(String codDer) {
    this.codDer = codDer;
  }

  public E075der desCpl(String desCpl) {
    this.desCpl = desCpl;
    return this;
  }

   /**
   * Descrição complementar
   * @return desCpl
  **/
  @ApiModelProperty(value = "Descrição complementar")
  public String getDesCpl() {
    return desCpl;
  }

  public void setDesCpl(String desCpl) {
    this.desCpl = desCpl;
  }

  public E075der pesBru(Double pesBru) {
    this.pesBru = pesBru;
    return this;
  }

   /**
   * Peso bruto
   * @return pesBru
  **/
  @ApiModelProperty(value = "Peso bruto")
  public Double getPesBru() {
    return pesBru;
  }

  public void setPesBru(Double pesBru) {
    this.pesBru = pesBru;
  }

  public E075der dthger(OffsetDateTime dthger) {
    this.dthger = dthger;
    return this;
  }

   /**
   * 
   * @return dthger
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthger() {
    return dthger;
  }

  public void setDthger(OffsetDateTime dthger) {
    this.dthger = dthger;
  }

  public E075der e047ntg(E047ntg e047ntg) {
    this.e047ntg = e047ntg;
    return this;
  }

   /**
   * Get e047ntg
   * @return e047ntg
  **/
  @ApiModelProperty(value = "")
  public E047ntg getE047ntg() {
    return e047ntg;
  }

  public void setE047ntg(E047ntg e047ntg) {
    this.e047ntg = e047ntg;
  }

  public E075der sitDer(EnumSitReg sitDer) {
    this.sitDer = sitDer;
    return this;
  }

   /**
   * Get sitDer
   * @return sitDer
  **/
  @ApiModelProperty(required = true, value = "")
  public EnumSitReg getSitDer() {
    return sitDer;
  }

  public void setSitDer(EnumSitReg sitDer) {
    this.sitDer = sitDer;
  }

  public E075der dthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
    return this;
  }

   /**
   * 
   * @return dthalt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthalt() {
    return dthalt;
  }

  public void setDthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
  }

  public E075der e012fam(E012fam e012fam) {
    this.e012fam = e012fam;
    return this;
  }

   /**
   * Get e012fam
   * @return e012fam
  **/
  @ApiModelProperty(required = true, value = "")
  public E012fam getE012fam() {
    return e012fam;
  }

  public void setE012fam(E012fam e012fam) {
    this.e012fam = e012fam;
  }

  public E075der usuger(String usuger) {
    this.usuger = usuger;
    return this;
  }

   /**
   * 
   * @return usuger
  **/
  @ApiModelProperty(value = "")
  public String getUsuger() {
    return usuger;
  }

  public void setUsuger(String usuger) {
    this.usuger = usuger;
  }

  public E075der codGtn(String codGtn) {
    this.codGtn = codGtn;
    return this;
  }

   /**
   * Gtin uni. trib
   * @return codGtn
  **/
  @ApiModelProperty(value = "Gtin uni. trib")
  public String getCodGtn() {
    return codGtn;
  }

  public void setCodGtn(String codGtn) {
    this.codGtn = codGtn;
  }

  public E075der pesLiq(Double pesLiq) {
    this.pesLiq = pesLiq;
    return this;
  }

   /**
   * Peso líquido
   * @return pesLiq
  **/
  @ApiModelProperty(value = "Peso líquido")
  public Double getPesLiq() {
    return pesLiq;
  }

  public void setPesLiq(Double pesLiq) {
    this.pesLiq = pesLiq;
  }

  public E075der proEpe(EnumProEpe proEpe) {
    this.proEpe = proEpe;
    return this;
  }

   /**
   * Get proEpe
   * @return proEpe
  **/
  @ApiModelProperty(value = "")
  public EnumProEpe getProEpe() {
    return proEpe;
  }

  public void setProEpe(EnumProEpe proEpe) {
    this.proEpe = proEpe;
  }

  public E075der desDer(String desDer) {
    this.desDer = desDer;
    return this;
  }

   /**
   * Descrição
   * @return desDer
  **/
  @ApiModelProperty(required = true, value = "Descrição")
  public String getDesDer() {
    return desDer;
  }

  public void setDesDer(String desDer) {
    this.desDer = desDer;
  }

  public E075der e070emp(E070emp e070emp) {
    this.e070emp = e070emp;
    return this;
  }

   /**
   * Get e070emp
   * @return e070emp
  **/
  @ApiModelProperty(required = true, value = "")
  public E070emp getE070emp() {
    return e070emp;
  }

  public void setE070emp(E070emp e070emp) {
    this.e070emp = e070emp;
  }

  public E075der id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public E075der idePro(String idePro) {
    this.idePro = idePro;
    return this;
  }

   /**
   * Identificação produto
   * @return idePro
  **/
  @ApiModelProperty(value = "Identificação produto")
  public String getIdePro() {
    return idePro;
  }

  public void setIdePro(String idePro) {
    this.idePro = idePro;
  }

  public E075der e021mot(E021mot e021mot) {
    this.e021mot = e021mot;
    return this;
  }

   /**
   * Get e021mot
   * @return e021mot
  **/
  @ApiModelProperty(value = "")
  public E021mot getE021mot() {
    return e021mot;
  }

  public void setE021mot(E021mot e021mot) {
    this.e021mot = e021mot;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    E075der e075der = (E075der) o;
    return Objects.equals(this.usualt, e075der.usualt) &&
        Objects.equals(this.codBar, e075der.codBar) &&
        Objects.equals(this.codBa2, e075der.codBa2) &&
        Objects.equals(this.codRef, e075der.codRef) &&
        Objects.equals(this.excluido, e075der.excluido) &&
        Objects.equals(this.codDer, e075der.codDer) &&
        Objects.equals(this.desCpl, e075der.desCpl) &&
        Objects.equals(this.pesBru, e075der.pesBru) &&
        Objects.equals(this.dthger, e075der.dthger) &&
        Objects.equals(this.e047ntg, e075der.e047ntg) &&
        Objects.equals(this.sitDer, e075der.sitDer) &&
        Objects.equals(this.dthalt, e075der.dthalt) &&
        Objects.equals(this.e012fam, e075der.e012fam) &&
        Objects.equals(this.usuger, e075der.usuger) &&
        Objects.equals(this.codGtn, e075der.codGtn) &&
        Objects.equals(this.pesLiq, e075der.pesLiq) &&
        Objects.equals(this.proEpe, e075der.proEpe) &&
        Objects.equals(this.desDer, e075der.desDer) &&
        Objects.equals(this.e070emp, e075der.e070emp) &&
        Objects.equals(this.id, e075der.id) &&
        Objects.equals(this.idePro, e075der.idePro) &&
        Objects.equals(this.e021mot, e075der.e021mot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usualt, codBar, codBa2, codRef, excluido, codDer, desCpl, pesBru, dthger, e047ntg, sitDer, dthalt, e012fam, usuger, codGtn, pesLiq, proEpe, desDer, e070emp, id, idePro, e021mot);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class E075der {\n");
    
    sb.append("    usualt: ").append(toIndentedString(usualt)).append("\n");
    sb.append("    codBar: ").append(toIndentedString(codBar)).append("\n");
    sb.append("    codBa2: ").append(toIndentedString(codBa2)).append("\n");
    sb.append("    codRef: ").append(toIndentedString(codRef)).append("\n");
    sb.append("    excluido: ").append(toIndentedString(excluido)).append("\n");
    sb.append("    codDer: ").append(toIndentedString(codDer)).append("\n");
    sb.append("    desCpl: ").append(toIndentedString(desCpl)).append("\n");
    sb.append("    pesBru: ").append(toIndentedString(pesBru)).append("\n");
    sb.append("    dthger: ").append(toIndentedString(dthger)).append("\n");
    sb.append("    e047ntg: ").append(toIndentedString(e047ntg)).append("\n");
    sb.append("    sitDer: ").append(toIndentedString(sitDer)).append("\n");
    sb.append("    dthalt: ").append(toIndentedString(dthalt)).append("\n");
    sb.append("    e012fam: ").append(toIndentedString(e012fam)).append("\n");
    sb.append("    usuger: ").append(toIndentedString(usuger)).append("\n");
    sb.append("    codGtn: ").append(toIndentedString(codGtn)).append("\n");
    sb.append("    pesLiq: ").append(toIndentedString(pesLiq)).append("\n");
    sb.append("    proEpe: ").append(toIndentedString(proEpe)).append("\n");
    sb.append("    desDer: ").append(toIndentedString(desDer)).append("\n");
    sb.append("    e070emp: ").append(toIndentedString(e070emp)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    idePro: ").append(toIndentedString(idePro)).append("\n");
    sb.append("    e021mot: ").append(toIndentedString(e021mot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

