/*
 * Produto
 * Serviço de Produto do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.produto.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.erpx.fnd.produto.pojos.EnumSitReg;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * E076mar
 */

public class E076mar {
  @SerializedName("usualt")
  private String usualt = null;

  @SerializedName("nomMar")
  private String nomMar = null;

  @SerializedName("excluido")
  private Boolean excluido = null;

  @SerializedName("dthger")
  private OffsetDateTime dthger = null;

  @SerializedName("dthalt")
  private OffsetDateTime dthalt = null;

  @SerializedName("sitMar")
  private EnumSitReg sitMar = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("codMar")
  private String codMar = null;

  @SerializedName("usuger")
  private String usuger = null;

  public E076mar usualt(String usualt) {
    this.usualt = usualt;
    return this;
  }

   /**
   * 
   * @return usualt
  **/
  @ApiModelProperty(value = "")
  public String getUsualt() {
    return usualt;
  }

  public void setUsualt(String usualt) {
    this.usualt = usualt;
  }

  public E076mar nomMar(String nomMar) {
    this.nomMar = nomMar;
    return this;
  }

   /**
   * Nome da marca
   * @return nomMar
  **/
  @ApiModelProperty(required = true, value = "Nome da marca")
  public String getNomMar() {
    return nomMar;
  }

  public void setNomMar(String nomMar) {
    this.nomMar = nomMar;
  }

  public E076mar excluido(Boolean excluido) {
    this.excluido = excluido;
    return this;
  }

   /**
   * Indica se o registro foi excluído
   * @return excluido
  **/
  @ApiModelProperty(value = "Indica se o registro foi excluído")
  public Boolean isExcluido() {
    return excluido;
  }

  public void setExcluido(Boolean excluido) {
    this.excluido = excluido;
  }

  public E076mar dthger(OffsetDateTime dthger) {
    this.dthger = dthger;
    return this;
  }

   /**
   * 
   * @return dthger
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthger() {
    return dthger;
  }

  public void setDthger(OffsetDateTime dthger) {
    this.dthger = dthger;
  }

  public E076mar dthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
    return this;
  }

   /**
   * 
   * @return dthalt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthalt() {
    return dthalt;
  }

  public void setDthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
  }

  public E076mar sitMar(EnumSitReg sitMar) {
    this.sitMar = sitMar;
    return this;
  }

   /**
   * Get sitMar
   * @return sitMar
  **/
  @ApiModelProperty(required = true, value = "")
  public EnumSitReg getSitMar() {
    return sitMar;
  }

  public void setSitMar(EnumSitReg sitMar) {
    this.sitMar = sitMar;
  }

  public E076mar id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public E076mar codMar(String codMar) {
    this.codMar = codMar;
    return this;
  }

   /**
   * Código da marca/etiqueta vinculada a um produto ou a um pedido
   * @return codMar
  **/
  @ApiModelProperty(required = true, value = "Código da marca/etiqueta vinculada a um produto ou a um pedido")
  public String getCodMar() {
    return codMar;
  }

  public void setCodMar(String codMar) {
    this.codMar = codMar;
  }

  public E076mar usuger(String usuger) {
    this.usuger = usuger;
    return this;
  }

   /**
   * 
   * @return usuger
  **/
  @ApiModelProperty(value = "")
  public String getUsuger() {
    return usuger;
  }

  public void setUsuger(String usuger) {
    this.usuger = usuger;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    E076mar e076mar = (E076mar) o;
    return Objects.equals(this.usualt, e076mar.usualt) &&
        Objects.equals(this.nomMar, e076mar.nomMar) &&
        Objects.equals(this.excluido, e076mar.excluido) &&
        Objects.equals(this.dthger, e076mar.dthger) &&
        Objects.equals(this.dthalt, e076mar.dthalt) &&
        Objects.equals(this.sitMar, e076mar.sitMar) &&
        Objects.equals(this.id, e076mar.id) &&
        Objects.equals(this.codMar, e076mar.codMar) &&
        Objects.equals(this.usuger, e076mar.usuger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usualt, nomMar, excluido, dthger, dthalt, sitMar, id, codMar, usuger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class E076mar {\n");
    
    sb.append("    usualt: ").append(toIndentedString(usualt)).append("\n");
    sb.append("    nomMar: ").append(toIndentedString(nomMar)).append("\n");
    sb.append("    excluido: ").append(toIndentedString(excluido)).append("\n");
    sb.append("    dthger: ").append(toIndentedString(dthger)).append("\n");
    sb.append("    dthalt: ").append(toIndentedString(dthalt)).append("\n");
    sb.append("    sitMar: ").append(toIndentedString(sitMar)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    codMar: ").append(toIndentedString(codMar)).append("\n");
    sb.append("    usuger: ").append(toIndentedString(usuger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

