/*
 * Produto
 * Serviço de Produto do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.produto.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.erpx.fnd.produto.pojos.E084mas;
import br.com.senior.erpx.fnd.produto.pojos.EnumSitReg;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * E084cma
 */

public class E084cma {
  @SerializedName("usualt")
  private String usualt = null;

  @SerializedName("excluido")
  private Boolean excluido = null;

  @SerializedName("sitCma")
  private EnumSitReg sitCma = null;

  @SerializedName("e084mas")
  private E084mas e084mas = null;

  @SerializedName("dthger")
  private OffsetDateTime dthger = null;

  @SerializedName("codCma")
  private String codCma = null;

  @SerializedName("seqCma")
  private Integer seqCma = null;

  @SerializedName("abrCma")
  private String abrCma = null;

  @SerializedName("dthalt")
  private OffsetDateTime dthalt = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("desCma")
  private String desCma = null;

  @SerializedName("usuger")
  private String usuger = null;

  public E084cma usualt(String usualt) {
    this.usualt = usualt;
    return this;
  }

   /**
   * 
   * @return usualt
  **/
  @ApiModelProperty(value = "")
  public String getUsualt() {
    return usualt;
  }

  public void setUsualt(String usualt) {
    this.usualt = usualt;
  }

  public E084cma excluido(Boolean excluido) {
    this.excluido = excluido;
    return this;
  }

   /**
   * Indica se o registro foi excluído
   * @return excluido
  **/
  @ApiModelProperty(value = "Indica se o registro foi excluído")
  public Boolean isExcluido() {
    return excluido;
  }

  public void setExcluido(Boolean excluido) {
    this.excluido = excluido;
  }

  public E084cma sitCma(EnumSitReg sitCma) {
    this.sitCma = sitCma;
    return this;
  }

   /**
   * Get sitCma
   * @return sitCma
  **/
  @ApiModelProperty(value = "")
  public EnumSitReg getSitCma() {
    return sitCma;
  }

  public void setSitCma(EnumSitReg sitCma) {
    this.sitCma = sitCma;
  }

  public E084cma e084mas(E084mas e084mas) {
    this.e084mas = e084mas;
    return this;
  }

   /**
   * Get e084mas
   * @return e084mas
  **/
  @ApiModelProperty(value = "")
  public E084mas getE084mas() {
    return e084mas;
  }

  public void setE084mas(E084mas e084mas) {
    this.e084mas = e084mas;
  }

  public E084cma dthger(OffsetDateTime dthger) {
    this.dthger = dthger;
    return this;
  }

   /**
   * 
   * @return dthger
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthger() {
    return dthger;
  }

  public void setDthger(OffsetDateTime dthger) {
    this.dthger = dthger;
  }

  public E084cma codCma(String codCma) {
    this.codCma = codCma;
    return this;
  }

   /**
   * Código do componente da máscara
   * @return codCma
  **/
  @ApiModelProperty(required = true, value = "Código do componente da máscara")
  public String getCodCma() {
    return codCma;
  }

  public void setCodCma(String codCma) {
    this.codCma = codCma;
  }

  public E084cma seqCma(Integer seqCma) {
    this.seqCma = seqCma;
    return this;
  }

   /**
   * Sequência
   * @return seqCma
  **/
  @ApiModelProperty(required = true, value = "Sequência")
  public Integer getSeqCma() {
    return seqCma;
  }

  public void setSeqCma(Integer seqCma) {
    this.seqCma = seqCma;
  }

  public E084cma abrCma(String abrCma) {
    this.abrCma = abrCma;
    return this;
  }

   /**
   * Abreviatura
   * @return abrCma
  **/
  @ApiModelProperty(required = true, value = "Abreviatura")
  public String getAbrCma() {
    return abrCma;
  }

  public void setAbrCma(String abrCma) {
    this.abrCma = abrCma;
  }

  public E084cma dthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
    return this;
  }

   /**
   * 
   * @return dthalt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDthalt() {
    return dthalt;
  }

  public void setDthalt(OffsetDateTime dthalt) {
    this.dthalt = dthalt;
  }

  public E084cma id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public E084cma desCma(String desCma) {
    this.desCma = desCma;
    return this;
  }

   /**
   * Descrição
   * @return desCma
  **/
  @ApiModelProperty(required = true, value = "Descrição")
  public String getDesCma() {
    return desCma;
  }

  public void setDesCma(String desCma) {
    this.desCma = desCma;
  }

  public E084cma usuger(String usuger) {
    this.usuger = usuger;
    return this;
  }

   /**
   * 
   * @return usuger
  **/
  @ApiModelProperty(value = "")
  public String getUsuger() {
    return usuger;
  }

  public void setUsuger(String usuger) {
    this.usuger = usuger;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    E084cma e084cma = (E084cma) o;
    return Objects.equals(this.usualt, e084cma.usualt) &&
        Objects.equals(this.excluido, e084cma.excluido) &&
        Objects.equals(this.sitCma, e084cma.sitCma) &&
        Objects.equals(this.e084mas, e084cma.e084mas) &&
        Objects.equals(this.dthger, e084cma.dthger) &&
        Objects.equals(this.codCma, e084cma.codCma) &&
        Objects.equals(this.seqCma, e084cma.seqCma) &&
        Objects.equals(this.abrCma, e084cma.abrCma) &&
        Objects.equals(this.dthalt, e084cma.dthalt) &&
        Objects.equals(this.id, e084cma.id) &&
        Objects.equals(this.desCma, e084cma.desCma) &&
        Objects.equals(this.usuger, e084cma.usuger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usualt, excluido, sitCma, e084mas, dthger, codCma, seqCma, abrCma, dthalt, id, desCma, usuger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class E084cma {\n");
    
    sb.append("    usualt: ").append(toIndentedString(usualt)).append("\n");
    sb.append("    excluido: ").append(toIndentedString(excluido)).append("\n");
    sb.append("    sitCma: ").append(toIndentedString(sitCma)).append("\n");
    sb.append("    e084mas: ").append(toIndentedString(e084mas)).append("\n");
    sb.append("    dthger: ").append(toIndentedString(dthger)).append("\n");
    sb.append("    codCma: ").append(toIndentedString(codCma)).append("\n");
    sb.append("    seqCma: ").append(toIndentedString(seqCma)).append("\n");
    sb.append("    abrCma: ").append(toIndentedString(abrCma)).append("\n");
    sb.append("    dthalt: ").append(toIndentedString(dthalt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    desCma: ").append(toIndentedString(desCma)).append("\n");
    sb.append("    usuger: ").append(toIndentedString(usuger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

