/*
 * Produto
 * Serviço de Produto do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.produto.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets enumTipNtg
 */
@JsonAdapter(EnumTipNtg.Adapter.class)
public enum EnumTipNtg {
  
  VN("VN"),
  
  VT("VT"),
  
  VR("VR");

  private String value;

  EnumTipNtg(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EnumTipNtg fromValue(String text) {
    for (EnumTipNtg b : EnumTipNtg.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<EnumTipNtg> {
    @Override
    public void write(final JsonWriter jsonWriter, final EnumTipNtg enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EnumTipNtg read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EnumTipNtg.fromValue(String.valueOf(value));
    }
  }
}

