/*
 * Produto
 * Serviço de Produto do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.erpx.fnd.produto.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets enumSitReg
 */
@JsonAdapter(EnumSitReg.Adapter.class)
public enum EnumSitReg {
  
  VA("VA"),
  
  VI("VI");

  private String value;

  EnumSitReg(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EnumSitReg fromValue(String text) {
    for (EnumSitReg b : EnumSitReg.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<EnumSitReg> {
    @Override
    public void write(final JsonWriter jsonWriter, final EnumSitReg enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EnumSitReg read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EnumSitReg.fromValue(String.valueOf(value));
    }
  }
}

